### ISSUE TITLE
Invalid inputs (per function declaration), throw Exceptions

### ISSUE THREAD

**Issue by kroy-the-rabbit** [kroy-the-rabbit/bofhbot_py#2]
See: `!flip asdf`

```
Ignoring exception in command flip:
Traceback (most recent call last):
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 467, in _actual_conversion
    return converter(argument)
ValueError: invalid literal for int() with base 10: 'asdf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 851, in invoke
    await self.prepare(ctx)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 786, in prepare
    await self._parse_arguments(ctx)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 552, in transform
    return await self.do_conversion(ctx, converter, argument, param)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 505, in do_conversion
    return await self._actual_conversion(ctx, converter, argument, param)
  File "/home/kroy/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 476, in _actual_conversion
    raise BadArgument('Converting to "{}" failed for parameter "{}".'.format(name, param.name)) from exc
discord.ext.commands.errors.BadArgument: Converting to "int" failed for parameter "limit".

```

**Comment by kroy-the-rabbit** [comment]
This isn't REALLY an issue beyond logspam, but should be caught/tossed/logged/etc
